# Generated by Django 4.1.4 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='gc_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
