# Generated by Django 4.1.4 on 2023-02-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_goodscategory_desc_goodscategory_gc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='property',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
