# Generated by Django 4.1.4 on 2023-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_alter_goods_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poduct',
            fields=[
                ('id', models.CharField(default='', max_length=6, primary_key=True, serialize=False)),
                ('model', models.CharField(default='', max_length=100)),
                ('Case', models.CharField(default='', max_length=100)),
                ('equipment', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=20)),
                ('Memory', models.CharField(default='', max_length=50)),
                ('SmartWatch', models.CharField(default='', max_length=50)),
                ('imember', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
    ]
