# Generated by Django 4.1.4 on 2023-02-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_poduct_delete_customer_remove_goods_goodscategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduct',
            new_name='Product',
        ),
    ]
