# Generated by Django 4.1.4 on 2023-02-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0006_customer_goodscategory_order_orderdetail_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='GoodsCategory',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='GoodsCategory',
        ),
    ]
